import React from "react";
import { Link } from "react-router-dom";
import MetricsGrid from "../components/MetricsGrid";
import EquityCurveChart from "../components/EquityCurveChart";
import DrawdownChart from "../components/DrawdownChart";
import AnnualReturnsChart from "../components/AnnualReturnsChart";
import RollingSharpeChart from "../components/RollingSharpeChart";
import demo from "../demoData.json";

/**
 * A real result, no login required.
 *
 * The numbers are a genuine run of the shipped engine on AAPL 2019–2024,
 * generated by the same code path the app uses and frozen into JSON — not
 * invented figures chosen to look good. It happens to show momentum badly
 * losing to buy-and-hold, which is the honest thing to lead with for a product
 * whose whole argument is that backtests flatter themselves.
 */
export default function DemoPage() {
  const strategyEnd = demo.equity_curve[demo.equity_curve.length - 1].strategy;
  const benchmarkEnd = demo.equity_curve[demo.equity_curve.length - 1].benchmark;

  return (
    <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
      <div className="flex items-start justify-between gap-4 flex-wrap mb-6">
        <div>
          <p className="eyebrow mb-3">Live sample · no account needed</p>
          <h1 className="text-2xl sm:text-3xl font-bold tracking-tight text-text-primary">
            Momentum on {demo.ticker}, {demo.start.slice(0, 4)}–{demo.end.slice(0, 4)}
          </h1>
          <p className="text-sm text-text-muted mt-1">
            {demo.bars} trading days · {demo.signals_summary.long_days}d long ·{" "}
            {demo.signals_summary.short_days}d short ·{" "}
            {demo.signals_summary.flat_days}d flat
          </p>
        </div>
        <Link
          to="/register"
          className="btn-primary px-5 py-2.5 text-sm"
        >
          Run your own
        </Link>
      </div>

      <div className="bg-warning/[0.06] border border-warning/25 rounded-xl px-5 py-4 mb-6">
        <p className="text-sm text-text-primary font-semibold mb-1">
          This strategy lost badly to doing nothing.
        </p>
        <p className="text-xs text-text-muted leading-relaxed">
          The strategy turned $1 into ${strategyEnd.toFixed(2)}. Buying and
          holding {demo.ticker} over the same period turned it into $
          {benchmarkEnd.toFixed(2)} — roughly{" "}
          {(benchmarkEnd / strategyEnd).toFixed(1)}× better, with no trading and
          no fees. We lead with this because it is the result the engine actually
          produced, and because a backtesting tool that only ever shows you
          winners is not measuring anything.
        </p>
      </div>

      <div className="flex flex-col gap-5">
        <MetricsGrid metrics={demo.metrics} />
        <EquityCurveChart data={demo.equity_curve} />
        <DrawdownChart data={demo.drawdown} />
        <AnnualReturnsChart data={demo.annual_returns} />
        <RollingSharpeChart data={demo.rolling_sharpe} />
      </div>

      <div className="mt-8 panel p-6">
        <h2 className="text-sm font-semibold text-text-primary mb-3">
          What you can't see here
        </h2>
        <p className="text-sm text-text-muted leading-relaxed mb-4">
          This is one strategy, one ticker, one period, with parameters nobody
          tuned. The question that decides whether any of it means anything is
          whether the result survives on data the parameters were never fitted
          to — that is what walk-forward validation and the permutation test
          answer, and they need an account to run.
        </p>
        <div className="flex items-center gap-3 flex-wrap">
          <Link
            to="/register"
            className="btn-primary px-5 py-2 text-sm"
          >
            Create a free account
          </Link>
          <Link
            to="/docs"
            className="btn-secondary px-5 py-2 text-sm"
          >
            How it works
          </Link>
        </div>
      </div>
    </div>
  );
}
